### ISSUE TITLE
Masthead height being used for width

### ISSUE THREAD

**Issue by lostmarinero** [twilio-labs/paste-prototype-kit#10]
Saw that the masthead height here is being used for width - is the height used for the width in this case? Thanks!

https://github.com/twilio-labs/paste-prototype-kit/blob/6d9e6aa3faca7565688276ef9ac73b3f0ee406dd/components/site/SiteMain.js#L9

**Comment by SiTaggart** [comment]
Potentially a silly mistake or some sweet, sweet copy pasta. Doesn't make any sense to be like that.

**Comment by TheSisb** [comment]
Resolved in https://github.com/twilio-labs/paste-prototype-kit/pull/22
